import { readdirSync, readFileSync } from "node:fs";

// Every migration plus the seed in one script, for pasting into the Supabase
// SQL editor on a fresh project. It also records the migrations in Supabase's
// migration history so `supabase db push` later knows they are applied.

const quote = (s: string) => `'${s.replace(/'/g, "''")}'`;

export function bootstrapSql(supabaseDir: URL): string {
  const files = readdirSync(new URL("migrations/", supabaseDir)).filter((f) => f.endsWith(".sql")).sort();
  const parts = [
    "-- Generated by `pnpm --filter @flowsim/db gen:bootstrap`. Do not edit by hand.",
    "-- Fresh Supabase project only: paste into the SQL editor and run once.",
    "begin;",
    "create schema if not exists supabase_migrations;",
    "create table if not exists supabase_migrations.schema_migrations (version text primary key, statements text[], name text);",
    // Not exposed via the API, but enabling RLS keeps the SQL editor's safety check quiet.
    "alter table supabase_migrations.schema_migrations enable row level security;",
  ];
  for (const f of files) {
    const sql = readFileSync(new URL(`migrations/${f}`, supabaseDir), "utf8");
    const [version, ...rest] = f.replace(/\.sql$/, "").split("_");
    parts.push(`\n-- ${f}\n${sql}`);
    parts.push(
      `insert into supabase_migrations.schema_migrations (version, name, statements) values (${quote(version!)}, ${quote(rest.join("_"))}, array[${quote(sql)}]);`,
    );
  }
  parts.push(`\n-- seed.sql\n${readFileSync(new URL("seed.sql", supabaseDir), "utf8")}`);
  parts.push("commit;\n");
  return parts.join("\n");
}
