import type { ProcessBundle, WorkspaceAccess } from "./types";

type Value = string | number | boolean | null | object;

function literal(v: Value): string {
  if (v === null) return "null";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  const text = typeof v === "object" ? JSON.stringify(v) : v;
  return `'${text.replace(/'/g, "''")}'`;
}

function insert(table: string, rows: Record<string, Value>[]): string {
  if (!rows.length) return "";
  const cols = Object.keys(rows[0]!);
  const values = rows.map((r) => `  (${cols.map((c) => literal(r[c] ?? null)).join(", ")})`).join(",\n");
  return `insert into public.${table} (${cols.join(", ")}) values\n${values};\n`;
}

/** SQL that inserts a process bundle. The process is linked to its revision last. */
export function seedSql(bundles: ProcessBundle[], access: WorkspaceAccess[] = []): string {
  const out: string[] = ["-- Generated by `pnpm --filter @transpera-flow/db gen:seed`. Do not edit by hand.\n"];
  for (const b of bundles) {
    out.push(`-- ${b.workspace.name}\n`);
    out.push(insert("workspaces", [{ id: b.workspace.id, name: b.workspace.name, slug: b.workspace.slug, settings: b.workspace.settings }]));
    out.push(insert("roles", b.roles.map((r) => ({ ...r }))));
    out.push(insert("people", b.people.map((r) => ({ ...r }))));
    out.push(insert("person_roles", b.personRoles.map((r) => ({ ...r }))));
    const { live_revision_id, ...process } = b.process;
    out.push(insert("processes", [process]));
    out.push(insert("process_revisions", [{ ...b.revision, published_at: b.revision.status === "published" ? "2026-09-29T00:00:00Z" : null }]));
    out.push(insert("steps", b.steps.map((s) => ({ ...s }))));
    out.push(insert("edges", b.edges.map((e) => ({ ...e }))));
    out.push(insert("person_skills", b.personSkills.map((r) => ({ ...r }))));
    out.push(insert("person_leave", b.personLeave.map((r) => ({ ...r }))));
    out.push(`update public.processes set live_revision_id = ${literal(live_revision_id)} where id = ${literal(b.process.id)};\n`);
  }
  for (const a of access) {
    out.push("-- Access: allowed domains and pre-assigned emails\n");
    out.push(insert("workspace_domains", a.domains.map((r) => ({ ...r }))));
    out.push(insert("workspace_access_emails", a.emails.map((r) => ({ ...r }))));
  }
  return out.join("\n");
}
