import { storedStatus } from "@transpera-flow/db/issue-status";
import type { NewSourceLink } from "./source-links";
import type { IssueRow, ProcessBundle, ScenarioRow, SourceRow, WorkspaceAccess } from "./types";

type Value = string | number | boolean | null | object;

function literal(v: Value): string {
  if (v === null) return "null";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  // Arrays of strings are text[] columns (e.g. services.path_tags); other objects are jsonb.
  if (Array.isArray(v) && v.every((x) => typeof x === "string")) return `array[${v.map(literal).join(", ")}]::text[]`;
  const text = typeof v === "object" ? JSON.stringify(v) : v;
  return `'${text.replace(/'/g, "''")}'`;
}

function insert(table: string, rows: Record<string, Value>[]): string {
  if (!rows.length) return "";
  const cols = Object.keys(rows[0]!);
  const values = rows.map((r) => `  (${cols.map((c) => literal(r[c] ?? null)).join(", ")})`).join(",\n");
  return `insert into public.${table} (${cols.join(", ")}) values\n${values};\n`;
}

/**
 * SQL that inserts process bundles, access settings, scenarios, issues and sources. The
 * process is linked to its revision last. Inserting a workspace gives it the
 * generic scenario library (a trigger); scenarios given for a workspace
 * replace it. Issues come last, as they can link a scenario.
 */
export function seedSql(
  bundles: ProcessBundle[],
  access: WorkspaceAccess[] = [],
  scenarios: ScenarioRow[] = [],
  issues: IssueRow[] = [],
  sources: SourceRow[] = [],
  sourceLinks: NewSourceLink[] = [],
): string {
  const out: string[] = ["-- Generated by `pnpm --filter @transpera-flow/db gen:seed`. Do not edit by hand.\n"];
  for (const b of bundles) {
    out.push(`-- ${b.workspace.name}\n`);
    out.push(insert("workspaces", [{ id: b.workspace.id, name: b.workspace.name, slug: b.workspace.slug, settings: b.workspace.settings }]));
    out.push(insert("roles", b.roles.map((r) => ({ ...r }))));
    out.push(insert("people", b.people.map((r) => ({ ...r }))));
    out.push(insert("person_roles", b.personRoles.map((r) => ({ ...r }))));
    const { live_revision_id, ...process } = b.process;
    // The workspace's other processes (servicing, issue #19), each linked to its live revision last, like the main one.
    const others = b.otherProcesses ?? [];
    out.push(insert("processes", [process, ...others.map(({ process: { live_revision_id: _live, ...p } }) => p)]));
    out.push(insert("services", b.services.map((r) => ({ ...r }))));
    out.push(insert("lead_sources", (b.leadSources ?? []).map((r) => ({ ...r }))));
    out.push(insert("seasonality", (b.seasonality ?? []).map((r) => ({ ...r }))));
    out.push(insert("demand_settings", b.demand ? [{ ...b.demand }] : []));
    out.push(insert("process_revisions", [{ ...b.revision, published_at: b.revision.status === "published" ? "2026-09-29T00:00:00Z" : null }]));
    out.push(insert("steps", b.steps.map((s) => ({ ...s }))));
    out.push(insert("edges", b.edges.map((e) => ({ ...e }))));
    for (const part of others) {
      out.push(insert("process_revisions", [{ ...part.revision, published_at: part.revision.status === "published" ? "2026-09-29T00:00:00Z" : null }]));
      out.push(insert("steps", part.steps.map((s) => ({ ...s }))));
      out.push(insert("edges", part.edges.map((e) => ({ ...e }))));
    }
    out.push(insert("service_servicing", (b.servicingLinks ?? []).map((r) => ({ ...r }))));
    out.push(insert("person_skills", b.personSkills.map((r) => ({ ...r }))));
    out.push(insert("person_leave", b.personLeave.map((r) => ({ ...r }))));
    out.push(insert("clients", (b.clients ?? []).map((r) => ({ ...r }))));
    out.push(insert("client_services", (b.clientServices ?? []).map((r) => ({ ...r }))));
    out.push(insert("client_assignments", (b.clientAssignments ?? []).map((r) => ({ ...r }))));
    out.push(insert("client_groups", (b.clientGroups ?? []).map((r) => ({ ...r }))));
    out.push(`update public.processes set live_revision_id = ${literal(live_revision_id)} where id = ${literal(b.process.id)};\n`);
    for (const { process: p } of others) {
      if (p.live_revision_id) out.push(`update public.processes set live_revision_id = ${literal(p.live_revision_id)} where id = ${literal(p.id)};\n`);
    }
    // The workspace's company map (made by a trigger when the workspace went in, with a holder for each process as it
    // went in) is laid out afresh now every process is published, as the Overview used to compute it.
    out.push(`select private.relayout_company_map(${literal(b.workspace.id)});\n`);
  }
  for (const a of access) {
    out.push("-- Access: allowed domains and pre-assigned emails\n");
    out.push(insert("workspace_domains", a.domains.map((r) => ({ ...r }))));
    out.push(insert("workspace_access_emails", a.emails.map((r) => ({ ...r }))));
  }
  const libraries = [...new Set(scenarios.map((s) => s.workspace_id))];
  if (libraries.length) {
    out.push("-- Scenario library: replaces the generic one the workspace trigger created\n");
    out.push(`delete from public.scenarios where workspace_id in (${libraries.map(literal).join(", ")});\n`);
    out.push(insert("scenarios", scenarios.map((r) => ({ ...r }))));
  }
  if (sources.length) {
    out.push("-- Sources: what the audit recorded, which step values cite as evidence\n");
    out.push(insert("sources", sources.map((r) => ({ ...r }))));
  }
  if (issues.length) {
    out.push("-- Issues register: audit findings and a promoted detection\n");
    // resolved_at and number are set by the table's triggers (the fixtures are numbered in insert order). The status is
    // stored as the older spellings plus a resolution (issue-status.ts). An issue's first link and first owner are
    // seeded by a trigger from process_id, step_id and owner_person_id; the rest go in their own tables.
    out.push(
      insert(
        "issues",
        issues.map(({ resolved_at: _resolved, number: _number, links: _l, owner_ids: _o, source_ids: _s, status, ...r }) => ({ ...r, ...storedStatus(status) })),
      ),
    );
    const rel = <T extends Record<string, unknown>>(pick: (i: IssueRow) => T[]) => issues.flatMap((i) => pick(i).map((r) => ({ issue_id: i.id, workspace_id: i.workspace_id, ...r })));
    out.push(insert("issue_links", rel((i) => i.links.filter((l) => !(l.process_id === i.process_id && l.step_id === i.step_id)).map((l) => ({ ...l })))));
    out.push(insert("issue_owners", rel((i) => i.owner_ids.filter((id) => id !== i.owner_person_id).map((person_id) => ({ person_id })))));
    out.push(insert("issue_sources", rel((i) => i.source_ids.map((source_id) => ({ source_id })))));
  }
  if (sourceLinks.length) {
    out.push("-- Source links: what each source is evidence for (the step citations and issue sources above, as links)\n");
    // The citing steps and issue_sources above may already have made some of these through their triggers.
    out.push(insert("source_links", sourceLinks.map((r) => ({ ...r }))).replace(/;\n$/, " on conflict do nothing;\n"));
  }
  return out.join("\n");
}
