-- Generated by `pnpm --filter @flowsim/db gen:bootstrap`. Do not edit by hand.
-- Fresh Supabase project only: paste into the SQL editor and run once.
begin;
create schema if not exists supabase_migrations;
create table if not exists supabase_migrations.schema_migrations (version text primary key, statements text[], name text);
alter table supabase_migrations.schema_migrations enable row level security;

-- 20260929000000_init.sql
-- Walking skeleton schema (docs/PRD.md §5, §10): workspaces, memberships and
-- the tables needed to load and simulate a process. Every table carries
-- workspace_id and is protected by row-level security.

-- ---------------------------------------------------------------------------
-- Types and helpers
-- ---------------------------------------------------------------------------

create type public.membership_role as enum ('agency_admin', 'owner', 'editor', 'member', 'viewer');

create function public.set_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table public.workspaces (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  plan text not null default 'agency',
  -- hours_per_week, horizon_weeks, currency, ... Interim demand fields
  -- (leads_per_week, active_clients, churn_monthly, retainer) live here until
  -- lead sources, services and the client roster land.
  settings jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users (id) on delete set null default auth.uid()
);

create table public.memberships (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role public.membership_role not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users (id) on delete set null default auth.uid(),
  unique (workspace_id, user_id)
);

create table public.roles (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  name text not null,
  color text,
  default_cost_rate numeric not null default 0 check (default_cost_rate >= 0),
  -- Interim until named people replace head-counts.
  headcount integer not null default 1 check (headcount >= 0),
  -- Interim until the client roster and servicing processes land.
  ongoing_hours_per_client_week numeric not null default 0 check (ongoing_hours_per_client_week >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users (id) on delete set null default auth.uid(),
  unique (id, workspace_id)
);

create table public.processes (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  name text not null,
  kind text not null default 'pipeline' check (kind in ('pipeline', 'servicing')),
  entity_name text not null default 'item',
  description text,
  live_revision_id uuid,
  draft_revision_id uuid,
  source text not null default 'manual' check (source in ('manual', 'template', 'mcp', 'import')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users (id) on delete set null default auth.uid(),
  unique (id, workspace_id)
);

create table public.process_revisions (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null,
  process_id uuid not null,
  number integer not null check (number > 0),
  status text not null default 'draft' check (status in ('draft', 'published', 'superseded')),
  layout jsonb not null default '{}',
  published_at timestamptz,
  published_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users (id) on delete set null default auth.uid(),
  unique (process_id, number),
  unique (id, workspace_id),
  foreign key (process_id, workspace_id) references public.processes (id, workspace_id) on delete cascade
);

alter table public.processes
  add foreign key (live_revision_id) references public.process_revisions (id) on delete set null deferrable initially deferred,
  add foreign key (draft_revision_id) references public.process_revisions (id) on delete set null deferrable initially deferred;

-- Step ids are stable across revisions, so the key is (revision_id, id).
create table public.steps (
  id uuid not null default gen_random_uuid(),
  revision_id uuid not null,
  workspace_id uuid not null,
  process_id uuid not null,
  name text not null,
  kind text not null default 'task' check (kind in ('task', 'wait', 'decision', 'subprocess', 'start', 'end')),
  outcome text check (outcome in ('won', 'lost', 'done')),
  role_id uuid,
  person_id uuid,
  work_hours numeric not null default 0 check (work_hours >= 0),
  work_dist text not null default 'lognormal' check (work_dist in ('constant', 'triangular', 'lognormal')),
  work_params jsonb not null default '{}',
  wait_hours numeric not null default 0 check (wait_hours >= 0),
  wait_dist text not null default 'lognormal' check (wait_dist in ('constant', 'triangular', 'lognormal')),
  wait_params jsonb not null default '{}',
  rework_rate numeric not null default 0 check (rework_rate >= 0 and rework_rate <= 1),
  rework_to_step_id uuid,
  tool text,
  notes text,
  sla_hours numeric check (sla_hours >= 0),
  current_wip integer check (current_wip >= 0),
  cost_override numeric,
  x numeric not null default 0,
  y numeric not null default 0,
  provenance jsonb not null default '{}',
  assumption boolean not null default false,
  conflict boolean not null default false,
  replaced_by uuid[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users (id) on delete set null default auth.uid(),
  primary key (revision_id, id),
  foreign key (revision_id, workspace_id) references public.process_revisions (id, workspace_id) on delete cascade,
  foreign key (role_id, workspace_id) references public.roles (id, workspace_id),
  check ((kind = 'end') = (outcome is not null))
);

create table public.edges (
  id uuid not null default gen_random_uuid(),
  revision_id uuid not null,
  workspace_id uuid not null,
  process_id uuid not null,
  from_step_id uuid not null,
  to_step_id uuid not null,
  probability numeric not null default 1 check (probability >= 0 and probability <= 1),
  condition_tag text,
  label text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users (id) on delete set null default auth.uid(),
  primary key (revision_id, id),
  foreign key (revision_id, workspace_id) references public.process_revisions (id, workspace_id) on delete cascade,
  foreign key (revision_id, from_step_id) references public.steps (revision_id, id) on delete cascade,
  foreign key (revision_id, to_step_id) references public.steps (revision_id, id) on delete cascade
);

create index on public.memberships (user_id);
create index on public.roles (workspace_id);
create index on public.processes (workspace_id);
create index on public.process_revisions (process_id);
create index on public.steps (workspace_id);
create index on public.edges (workspace_id);

create trigger set_updated_at before update on public.workspaces for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.memberships for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.roles for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.processes for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.process_revisions for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.steps for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.edges for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Access helpers. Agency admins are marked by an `agency_admin` flag in the
-- user's app_metadata (only settable with the service role) and see every
-- workspace; everyone else needs a membership.
-- ---------------------------------------------------------------------------

create function public.is_agency_admin() returns boolean
language sql stable
set search_path = ''
as $$
  select coalesce((auth.jwt() -> 'app_metadata' ->> 'agency_admin')::boolean, false);
$$;

create function public.workspace_role(ws uuid) returns public.membership_role
language sql stable security definer
set search_path = ''
as $$
  select m.role from public.memberships m where m.workspace_id = ws and m.user_id = auth.uid();
$$;

create function public.can_read_workspace(ws uuid) returns boolean
language sql stable
set search_path = ''
as $$
  select public.is_agency_admin() or public.workspace_role(ws) is not null;
$$;

create function public.can_edit_workspace(ws uuid) returns boolean
language sql stable
set search_path = ''
as $$
  select public.is_agency_admin() or public.workspace_role(ws) in ('agency_admin', 'owner', 'editor');
$$;

create function public.can_manage_workspace(ws uuid) returns boolean
language sql stable
set search_path = ''
as $$
  select public.is_agency_admin() or public.workspace_role(ws) in ('agency_admin', 'owner');
$$;

-- ---------------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------------

alter table public.workspaces enable row level security;
alter table public.memberships enable row level security;
alter table public.roles enable row level security;
alter table public.processes enable row level security;
alter table public.process_revisions enable row level security;
alter table public.steps enable row level security;
alter table public.edges enable row level security;

create policy "read workspaces" on public.workspaces for select to authenticated
  using (public.can_read_workspace(id));
create policy "create workspaces" on public.workspaces for insert to authenticated
  with check (public.is_agency_admin());
create policy "update workspaces" on public.workspaces for update to authenticated
  using (public.can_manage_workspace(id)) with check (public.can_manage_workspace(id));
create policy "delete workspaces" on public.workspaces for delete to authenticated
  using (public.is_agency_admin());

create policy "read memberships" on public.memberships for select to authenticated
  using (public.can_read_workspace(workspace_id));
create policy "manage memberships" on public.memberships for all to authenticated
  using (public.can_manage_workspace(workspace_id)) with check (public.can_manage_workspace(workspace_id));

do $$
declare
  t text;
begin
  foreach t in array array['roles', 'processes', 'process_revisions', 'steps', 'edges'] loop
    execute format(
      'create policy "read %1$s" on public.%1$I for select to authenticated using (public.can_read_workspace(workspace_id))', t);
    execute format(
      'create policy "insert %1$s" on public.%1$I for insert to authenticated with check (public.can_edit_workspace(workspace_id))', t);
    execute format(
      'create policy "update %1$s" on public.%1$I for update to authenticated using (public.can_edit_workspace(workspace_id)) with check (public.can_edit_workspace(workspace_id))', t);
    execute format(
      'create policy "delete %1$s" on public.%1$I for delete to authenticated using (public.can_edit_workspace(workspace_id))', t);
  end loop;
end;
$$;

grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
revoke all on all tables in schema public from anon;

insert into supabase_migrations.schema_migrations (version, name, statements) values ('20260929000000', 'init', array['-- Walking skeleton schema (docs/PRD.md §5, §10): workspaces, memberships and
-- the tables needed to load and simulate a process. Every table carries
-- workspace_id and is protected by row-level security.

-- ---------------------------------------------------------------------------
-- Types and helpers
-- ---------------------------------------------------------------------------

create type public.membership_role as enum (''agency_admin'', ''owner'', ''editor'', ''member'', ''viewer'');

create function public.set_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table public.workspaces (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique check (slug ~ ''^[a-z0-9]+(-[a-z0-9]+)*$''),
  plan text not null default ''agency'',
  -- hours_per_week, horizon_weeks, currency, ... Interim demand fields
  -- (leads_per_week, active_clients, churn_monthly, retainer) live here until
  -- lead sources, services and the client roster land.
  settings jsonb not null default ''{}'',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users (id) on delete set null default auth.uid()
);

create table public.memberships (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role public.membership_role not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users (id) on delete set null default auth.uid(),
  unique (workspace_id, user_id)
);

create table public.roles (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  name text not null,
  color text,
  default_cost_rate numeric not null default 0 check (default_cost_rate >= 0),
  -- Interim until named people replace head-counts.
  headcount integer not null default 1 check (headcount >= 0),
  -- Interim until the client roster and servicing processes land.
  ongoing_hours_per_client_week numeric not null default 0 check (ongoing_hours_per_client_week >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users (id) on delete set null default auth.uid(),
  unique (id, workspace_id)
);

create table public.processes (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  name text not null,
  kind text not null default ''pipeline'' check (kind in (''pipeline'', ''servicing'')),
  entity_name text not null default ''item'',
  description text,
  live_revision_id uuid,
  draft_revision_id uuid,
  source text not null default ''manual'' check (source in (''manual'', ''template'', ''mcp'', ''import'')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users (id) on delete set null default auth.uid(),
  unique (id, workspace_id)
);

create table public.process_revisions (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null,
  process_id uuid not null,
  number integer not null check (number > 0),
  status text not null default ''draft'' check (status in (''draft'', ''published'', ''superseded'')),
  layout jsonb not null default ''{}'',
  published_at timestamptz,
  published_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users (id) on delete set null default auth.uid(),
  unique (process_id, number),
  unique (id, workspace_id),
  foreign key (process_id, workspace_id) references public.processes (id, workspace_id) on delete cascade
);

alter table public.processes
  add foreign key (live_revision_id) references public.process_revisions (id) on delete set null deferrable initially deferred,
  add foreign key (draft_revision_id) references public.process_revisions (id) on delete set null deferrable initially deferred;

-- Step ids are stable across revisions, so the key is (revision_id, id).
create table public.steps (
  id uuid not null default gen_random_uuid(),
  revision_id uuid not null,
  workspace_id uuid not null,
  process_id uuid not null,
  name text not null,
  kind text not null default ''task'' check (kind in (''task'', ''wait'', ''decision'', ''subprocess'', ''start'', ''end'')),
  outcome text check (outcome in (''won'', ''lost'', ''done'')),
  role_id uuid,
  person_id uuid,
  work_hours numeric not null default 0 check (work_hours >= 0),
  work_dist text not null default ''lognormal'' check (work_dist in (''constant'', ''triangular'', ''lognormal'')),
  work_params jsonb not null default ''{}'',
  wait_hours numeric not null default 0 check (wait_hours >= 0),
  wait_dist text not null default ''lognormal'' check (wait_dist in (''constant'', ''triangular'', ''lognormal'')),
  wait_params jsonb not null default ''{}'',
  rework_rate numeric not null default 0 check (rework_rate >= 0 and rework_rate <= 1),
  rework_to_step_id uuid,
  tool text,
  notes text,
  sla_hours numeric check (sla_hours >= 0),
  current_wip integer check (current_wip >= 0),
  cost_override numeric,
  x numeric not null default 0,
  y numeric not null default 0,
  provenance jsonb not null default ''{}'',
  assumption boolean not null default false,
  conflict boolean not null default false,
  replaced_by uuid[] not null default ''{}'',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users (id) on delete set null default auth.uid(),
  primary key (revision_id, id),
  foreign key (revision_id, workspace_id) references public.process_revisions (id, workspace_id) on delete cascade,
  foreign key (role_id, workspace_id) references public.roles (id, workspace_id),
  check ((kind = ''end'') = (outcome is not null))
);

create table public.edges (
  id uuid not null default gen_random_uuid(),
  revision_id uuid not null,
  workspace_id uuid not null,
  process_id uuid not null,
  from_step_id uuid not null,
  to_step_id uuid not null,
  probability numeric not null default 1 check (probability >= 0 and probability <= 1),
  condition_tag text,
  label text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users (id) on delete set null default auth.uid(),
  primary key (revision_id, id),
  foreign key (revision_id, workspace_id) references public.process_revisions (id, workspace_id) on delete cascade,
  foreign key (revision_id, from_step_id) references public.steps (revision_id, id) on delete cascade,
  foreign key (revision_id, to_step_id) references public.steps (revision_id, id) on delete cascade
);

create index on public.memberships (user_id);
create index on public.roles (workspace_id);
create index on public.processes (workspace_id);
create index on public.process_revisions (process_id);
create index on public.steps (workspace_id);
create index on public.edges (workspace_id);

create trigger set_updated_at before update on public.workspaces for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.memberships for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.roles for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.processes for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.process_revisions for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.steps for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.edges for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Access helpers. Agency admins are marked by an `agency_admin` flag in the
-- user''s app_metadata (only settable with the service role) and see every
-- workspace; everyone else needs a membership.
-- ---------------------------------------------------------------------------

create function public.is_agency_admin() returns boolean
language sql stable
set search_path = ''''
as $$
  select coalesce((auth.jwt() -> ''app_metadata'' ->> ''agency_admin'')::boolean, false);
$$;

create function public.workspace_role(ws uuid) returns public.membership_role
language sql stable security definer
set search_path = ''''
as $$
  select m.role from public.memberships m where m.workspace_id = ws and m.user_id = auth.uid();
$$;

create function public.can_read_workspace(ws uuid) returns boolean
language sql stable
set search_path = ''''
as $$
  select public.is_agency_admin() or public.workspace_role(ws) is not null;
$$;

create function public.can_edit_workspace(ws uuid) returns boolean
language sql stable
set search_path = ''''
as $$
  select public.is_agency_admin() or public.workspace_role(ws) in (''agency_admin'', ''owner'', ''editor'');
$$;

create function public.can_manage_workspace(ws uuid) returns boolean
language sql stable
set search_path = ''''
as $$
  select public.is_agency_admin() or public.workspace_role(ws) in (''agency_admin'', ''owner'');
$$;

-- ---------------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------------

alter table public.workspaces enable row level security;
alter table public.memberships enable row level security;
alter table public.roles enable row level security;
alter table public.processes enable row level security;
alter table public.process_revisions enable row level security;
alter table public.steps enable row level security;
alter table public.edges enable row level security;

create policy "read workspaces" on public.workspaces for select to authenticated
  using (public.can_read_workspace(id));
create policy "create workspaces" on public.workspaces for insert to authenticated
  with check (public.is_agency_admin());
create policy "update workspaces" on public.workspaces for update to authenticated
  using (public.can_manage_workspace(id)) with check (public.can_manage_workspace(id));
create policy "delete workspaces" on public.workspaces for delete to authenticated
  using (public.is_agency_admin());

create policy "read memberships" on public.memberships for select to authenticated
  using (public.can_read_workspace(workspace_id));
create policy "manage memberships" on public.memberships for all to authenticated
  using (public.can_manage_workspace(workspace_id)) with check (public.can_manage_workspace(workspace_id));

do $$
declare
  t text;
begin
  foreach t in array array[''roles'', ''processes'', ''process_revisions'', ''steps'', ''edges''] loop
    execute format(
      ''create policy "read %1$s" on public.%1$I for select to authenticated using (public.can_read_workspace(workspace_id))'', t);
    execute format(
      ''create policy "insert %1$s" on public.%1$I for insert to authenticated with check (public.can_edit_workspace(workspace_id))'', t);
    execute format(
      ''create policy "update %1$s" on public.%1$I for update to authenticated using (public.can_edit_workspace(workspace_id)) with check (public.can_edit_workspace(workspace_id))'', t);
    execute format(
      ''create policy "delete %1$s" on public.%1$I for delete to authenticated using (public.can_edit_workspace(workspace_id))'', t);
  end loop;
end;
$$;

grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
revoke all on all tables in schema public from anon;
']);

-- 20260929010000_people.sql
-- Named people as resources (docs/PRD.md §5, §6.3.3). People are modelled for
-- capacity, not performance: no efficiency is exposed yet (§6.3.7).

create table public.people (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  name text not null,
  email text,
  fte numeric not null default 1 check (fte > 0 and fte <= 1.5),
  -- Null means fte × the workspace's hours per week.
  capacity_hours_week numeric check (capacity_hours_week > 0),
  cost_rate numeric check (cost_rate >= 0),
  active boolean not null default true,
  start_date date,
  end_date date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users (id) on delete set null default auth.uid(),
  unique (id, workspace_id),
  check (end_date is null or start_date is null or end_date >= start_date)
);

create table public.person_roles (
  person_id uuid not null,
  role_id uuid not null,
  workspace_id uuid not null,
  created_at timestamptz not null default now(),
  primary key (person_id, role_id),
  foreign key (person_id, workspace_id) references public.people (id, workspace_id) on delete cascade,
  foreign key (role_id, workspace_id) references public.roles (id, workspace_id) on delete cascade
);

-- Steps a person can perform. A person with no rows here can do every step of their roles.
create table public.person_skills (
  person_id uuid not null,
  step_id uuid not null,
  workspace_id uuid not null,
  -- Capacity factor (off by default per workspace; §6.3.7). Not used by the engine yet.
  efficiency numeric not null default 1 check (efficiency > 0),
  provenance jsonb not null default '{}',
  created_at timestamptz not null default now(),
  primary key (person_id, step_id),
  foreign key (person_id, workspace_id) references public.people (id, workspace_id) on delete cascade
);

create table public.person_leave (
  id uuid primary key default gen_random_uuid(),
  person_id uuid not null,
  workspace_id uuid not null,
  start_date date not null,
  end_date date not null,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users (id) on delete set null default auth.uid(),
  foreign key (person_id, workspace_id) references public.people (id, workspace_id) on delete cascade,
  check (end_date >= start_date)
);

-- Pinned assignee on a step.
alter table public.steps
  add foreign key (person_id, workspace_id) references public.people (id, workspace_id);

create index on public.people (workspace_id);
create index on public.person_roles (workspace_id);
create index on public.person_skills (workspace_id);
create index on public.person_leave (person_id);

create trigger set_updated_at before update on public.people for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.person_leave for each row execute function public.set_updated_at();

alter table public.people enable row level security;
alter table public.person_roles enable row level security;
alter table public.person_skills enable row level security;
alter table public.person_leave enable row level security;

do $$
declare
  t text;
begin
  foreach t in array array['people', 'person_roles', 'person_skills', 'person_leave'] loop
    execute format(
      'create policy "read %1$s" on public.%1$I for select to authenticated using (public.can_read_workspace(workspace_id))', t);
    execute format(
      'create policy "insert %1$s" on public.%1$I for insert to authenticated with check (public.can_edit_workspace(workspace_id))', t);
    execute format(
      'create policy "update %1$s" on public.%1$I for update to authenticated using (public.can_edit_workspace(workspace_id)) with check (public.can_edit_workspace(workspace_id))', t);
    execute format(
      'create policy "delete %1$s" on public.%1$I for delete to authenticated using (public.can_edit_workspace(workspace_id))', t);
  end loop;
end;
$$;

grant select, insert, update, delete on public.people, public.person_roles, public.person_skills, public.person_leave to authenticated;
revoke all on public.people, public.person_roles, public.person_skills, public.person_leave from anon;

insert into supabase_migrations.schema_migrations (version, name, statements) values ('20260929010000', 'people', array['-- Named people as resources (docs/PRD.md §5, §6.3.3). People are modelled for
-- capacity, not performance: no efficiency is exposed yet (§6.3.7).

create table public.people (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces (id) on delete cascade,
  name text not null,
  email text,
  fte numeric not null default 1 check (fte > 0 and fte <= 1.5),
  -- Null means fte × the workspace''s hours per week.
  capacity_hours_week numeric check (capacity_hours_week > 0),
  cost_rate numeric check (cost_rate >= 0),
  active boolean not null default true,
  start_date date,
  end_date date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users (id) on delete set null default auth.uid(),
  unique (id, workspace_id),
  check (end_date is null or start_date is null or end_date >= start_date)
);

create table public.person_roles (
  person_id uuid not null,
  role_id uuid not null,
  workspace_id uuid not null,
  created_at timestamptz not null default now(),
  primary key (person_id, role_id),
  foreign key (person_id, workspace_id) references public.people (id, workspace_id) on delete cascade,
  foreign key (role_id, workspace_id) references public.roles (id, workspace_id) on delete cascade
);

-- Steps a person can perform. A person with no rows here can do every step of their roles.
create table public.person_skills (
  person_id uuid not null,
  step_id uuid not null,
  workspace_id uuid not null,
  -- Capacity factor (off by default per workspace; §6.3.7). Not used by the engine yet.
  efficiency numeric not null default 1 check (efficiency > 0),
  provenance jsonb not null default ''{}'',
  created_at timestamptz not null default now(),
  primary key (person_id, step_id),
  foreign key (person_id, workspace_id) references public.people (id, workspace_id) on delete cascade
);

create table public.person_leave (
  id uuid primary key default gen_random_uuid(),
  person_id uuid not null,
  workspace_id uuid not null,
  start_date date not null,
  end_date date not null,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users (id) on delete set null default auth.uid(),
  foreign key (person_id, workspace_id) references public.people (id, workspace_id) on delete cascade,
  check (end_date >= start_date)
);

-- Pinned assignee on a step.
alter table public.steps
  add foreign key (person_id, workspace_id) references public.people (id, workspace_id);

create index on public.people (workspace_id);
create index on public.person_roles (workspace_id);
create index on public.person_skills (workspace_id);
create index on public.person_leave (person_id);

create trigger set_updated_at before update on public.people for each row execute function public.set_updated_at();
create trigger set_updated_at before update on public.person_leave for each row execute function public.set_updated_at();

alter table public.people enable row level security;
alter table public.person_roles enable row level security;
alter table public.person_skills enable row level security;
alter table public.person_leave enable row level security;

do $$
declare
  t text;
begin
  foreach t in array array[''people'', ''person_roles'', ''person_skills'', ''person_leave''] loop
    execute format(
      ''create policy "read %1$s" on public.%1$I for select to authenticated using (public.can_read_workspace(workspace_id))'', t);
    execute format(
      ''create policy "insert %1$s" on public.%1$I for insert to authenticated with check (public.can_edit_workspace(workspace_id))'', t);
    execute format(
      ''create policy "update %1$s" on public.%1$I for update to authenticated using (public.can_edit_workspace(workspace_id)) with check (public.can_edit_workspace(workspace_id))'', t);
    execute format(
      ''create policy "delete %1$s" on public.%1$I for delete to authenticated using (public.can_edit_workspace(workspace_id))'', t);
  end loop;
end;
$$;

grant select, insert, update, delete on public.people, public.person_roles, public.person_skills, public.person_leave to authenticated;
revoke all on public.people, public.person_roles, public.person_skills, public.person_leave from anon;
']);

-- seed.sql
-- Generated by `pnpm --filter @flowsim/db gen:seed`. Do not edit by hand.

-- Northbeam Digital

insert into public.workspaces (id, name, slug, settings) values
  ('a0000000-0000-4000-8000-000000000001', 'Northbeam Digital', 'northbeam', '{"hours_per_week":40,"horizon_weeks":13,"currency":"GBP","leads_per_week":12,"active_clients":26,"churn_monthly":0.03,"retainer":3800}');

insert into public.roles (id, workspace_id, name, color, default_cost_rate, headcount, ongoing_hours_per_client_week) values
  ('b0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'Sales', '#2a78d6', 45, 2, 0),
  ('b0000000-0000-4000-8000-000000000002', 'a0000000-0000-4000-8000-000000000001', 'Strategist', '#eb6834', 70, 1, 0.4),
  ('b0000000-0000-4000-8000-000000000003', 'a0000000-0000-4000-8000-000000000001', 'Account manager', '#1baf7a', 55, 2, 1.6),
  ('b0000000-0000-4000-8000-000000000004', 'a0000000-0000-4000-8000-000000000001', 'SEO specialist', '#8b5cf6', 50, 3, 2.4),
  ('b0000000-0000-4000-8000-000000000005', 'a0000000-0000-4000-8000-000000000001', 'PPC specialist', '#d4a106', 50, 2, 2),
  ('b0000000-0000-4000-8000-000000000006', 'a0000000-0000-4000-8000-000000000001', 'Finance', '#64748b', 40, 1, 0.3);

insert into public.people (id, workspace_id, name, fte, capacity_hours_week, cost_rate, active, start_date, end_date) values
  ('90000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'Priya Shah', 1, null, null, true, null, null),
  ('90000000-0000-4000-8000-000000000002', 'a0000000-0000-4000-8000-000000000001', 'Tom Reed', 1, null, null, true, null, null),
  ('90000000-0000-4000-8000-000000000003', 'a0000000-0000-4000-8000-000000000001', 'Maya Collins', 1, null, null, true, null, null),
  ('90000000-0000-4000-8000-000000000004', 'a0000000-0000-4000-8000-000000000001', 'Leah Brooks', 1, null, null, true, null, null),
  ('90000000-0000-4000-8000-000000000005', 'a0000000-0000-4000-8000-000000000001', 'Dan Okafor', 1, null, null, true, null, null),
  ('90000000-0000-4000-8000-000000000006', 'a0000000-0000-4000-8000-000000000001', 'Sam Patel', 1, null, null, true, null, null),
  ('90000000-0000-4000-8000-000000000007', 'a0000000-0000-4000-8000-000000000001', 'Chloe Evans', 1, null, null, true, null, null),
  ('90000000-0000-4000-8000-000000000008', 'a0000000-0000-4000-8000-000000000001', 'Arjun Mehta', 1, null, null, true, null, null),
  ('90000000-0000-4000-8000-000000000009', 'a0000000-0000-4000-8000-000000000001', 'Nina Kowalski', 1, null, null, true, null, null),
  ('90000000-0000-4000-8000-00000000000a', 'a0000000-0000-4000-8000-000000000001', 'Ben Carter', 1, null, null, true, null, null),
  ('90000000-0000-4000-8000-00000000000b', 'a0000000-0000-4000-8000-000000000001', 'Rosa Diaz', 1, null, null, true, null, null);

insert into public.person_roles (person_id, role_id, workspace_id) values
  ('90000000-0000-4000-8000-000000000001', 'b0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001'),
  ('90000000-0000-4000-8000-000000000002', 'b0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001'),
  ('90000000-0000-4000-8000-000000000003', 'b0000000-0000-4000-8000-000000000002', 'a0000000-0000-4000-8000-000000000001'),
  ('90000000-0000-4000-8000-000000000004', 'b0000000-0000-4000-8000-000000000003', 'a0000000-0000-4000-8000-000000000001'),
  ('90000000-0000-4000-8000-000000000005', 'b0000000-0000-4000-8000-000000000003', 'a0000000-0000-4000-8000-000000000001'),
  ('90000000-0000-4000-8000-000000000006', 'b0000000-0000-4000-8000-000000000004', 'a0000000-0000-4000-8000-000000000001'),
  ('90000000-0000-4000-8000-000000000007', 'b0000000-0000-4000-8000-000000000004', 'a0000000-0000-4000-8000-000000000001'),
  ('90000000-0000-4000-8000-000000000008', 'b0000000-0000-4000-8000-000000000004', 'a0000000-0000-4000-8000-000000000001'),
  ('90000000-0000-4000-8000-000000000009', 'b0000000-0000-4000-8000-000000000005', 'a0000000-0000-4000-8000-000000000001'),
  ('90000000-0000-4000-8000-00000000000a', 'b0000000-0000-4000-8000-000000000005', 'a0000000-0000-4000-8000-000000000001'),
  ('90000000-0000-4000-8000-00000000000b', 'b0000000-0000-4000-8000-000000000006', 'a0000000-0000-4000-8000-000000000001');

insert into public.processes (id, workspace_id, name, kind, entity_name, description) values
  ('c0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'Lead to live', 'pipeline', 'lead', 'From inbound lead to a live SEO or PPC campaign.');

insert into public.process_revisions (id, workspace_id, process_id, number, status, published_at) values
  ('d0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 1, 'published', '2026-09-29T00:00:00Z');

insert into public.steps (id, revision_id, workspace_id, process_id, name, kind, outcome, role_id, person_id, work_hours, work_dist, wait_hours, wait_dist, rework_rate, tool, x, y) values
  ('e0000000-0000-4000-8000-000000000001', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'Qualify lead', 'task', null, 'b0000000-0000-4000-8000-000000000001', null, 0.5, 'lognormal', 4, 'lognormal', 0, 'HubSpot', 60, 50),
  ('e0000000-0000-4000-8000-000000000002', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'Discovery call', 'task', null, 'b0000000-0000-4000-8000-000000000001', null, 1.5, 'lognormal', 24, 'lognormal', 0, 'Zoom + HubSpot', 290, 50),
  ('e0000000-0000-4000-8000-000000000003', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'Audit & proposal', 'task', null, 'b0000000-0000-4000-8000-000000000002', null, 6, 'lognormal', 0, 'lognormal', 0.15, 'SEMrush, Google Docs', 520, 50),
  ('e0000000-0000-4000-8000-000000000004', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'Client decision', 'decision', null, null, null, 0, 'lognormal', 40, 'lognormal', 0, 'Email', 750, 50),
  ('e0000000-0000-4000-8000-000000000005', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'Contract & onboarding', 'task', null, 'b0000000-0000-4000-8000-000000000003', null, 3, 'lognormal', 16, 'lognormal', 0.1, 'PandaDoc, Notion', 60, 290),
  ('e0000000-0000-4000-8000-000000000006', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'Kickoff & strategy', 'task', null, 'b0000000-0000-4000-8000-000000000002', null, 4, 'lognormal', 8, 'lognormal', 0, 'Notion', 290, 290),
  ('e0000000-0000-4000-8000-000000000007', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'SEO campaign setup', 'task', null, 'b0000000-0000-4000-8000-000000000004', null, 10, 'lognormal', 8, 'lognormal', 0.1, 'Ahrefs, WordPress', 520, 230),
  ('e0000000-0000-4000-8000-000000000008', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'PPC campaign setup', 'task', null, 'b0000000-0000-4000-8000-000000000005', null, 8, 'lognormal', 8, 'lognormal', 0.1, 'Google Ads', 520, 340),
  ('e0000000-0000-4000-8000-000000000009', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'Go live & first report', 'task', null, 'b0000000-0000-4000-8000-000000000003', null, 2, 'lognormal', 0, 'lognormal', 0, 'Looker Studio', 750, 290),
  ('e0000000-0000-4000-8000-00000000000a', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'Lead arrives', 'start', null, null, null, 0, 'lognormal', 0, 'lognormal', 0, null, -150, 50),
  ('e0000000-0000-4000-8000-00000000000b', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'Won', 'end', 'won', null, null, 0, 'lognormal', 0, 'lognormal', 0, null, 980, 290),
  ('e0000000-0000-4000-8000-00000000000c', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'Lost', 'end', 'lost', null, null, 0, 'lognormal', 0, 'lognormal', 0, null, 640, 170);

insert into public.edges (id, revision_id, workspace_id, process_id, from_step_id, to_step_id, probability, condition_tag, label) values
  ('f0000000-0000-4000-8000-000000000001', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'e0000000-0000-4000-8000-00000000000a', 'e0000000-0000-4000-8000-000000000001', 1, null, null),
  ('f0000000-0000-4000-8000-000000000002', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'e0000000-0000-4000-8000-000000000001', 'e0000000-0000-4000-8000-000000000002', 0.55, null, null),
  ('f0000000-0000-4000-8000-000000000003', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'e0000000-0000-4000-8000-000000000001', 'e0000000-0000-4000-8000-00000000000c', 0.45, null, null),
  ('f0000000-0000-4000-8000-000000000004', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'e0000000-0000-4000-8000-000000000002', 'e0000000-0000-4000-8000-000000000003', 0.7, null, null),
  ('f0000000-0000-4000-8000-000000000005', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'e0000000-0000-4000-8000-000000000002', 'e0000000-0000-4000-8000-00000000000c', 0.3, null, null),
  ('f0000000-0000-4000-8000-000000000006', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'e0000000-0000-4000-8000-000000000003', 'e0000000-0000-4000-8000-000000000004', 1, null, null),
  ('f0000000-0000-4000-8000-000000000007', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'e0000000-0000-4000-8000-000000000004', 'e0000000-0000-4000-8000-000000000005', 0.32, null, null),
  ('f0000000-0000-4000-8000-000000000008', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'e0000000-0000-4000-8000-000000000004', 'e0000000-0000-4000-8000-00000000000c', 0.68, null, null),
  ('f0000000-0000-4000-8000-000000000009', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'e0000000-0000-4000-8000-000000000005', 'e0000000-0000-4000-8000-000000000006', 1, null, null),
  ('f0000000-0000-4000-8000-00000000000a', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'e0000000-0000-4000-8000-000000000006', 'e0000000-0000-4000-8000-000000000007', 0.55, null, null),
  ('f0000000-0000-4000-8000-00000000000b', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'e0000000-0000-4000-8000-000000000006', 'e0000000-0000-4000-8000-000000000008', 0.45, null, null),
  ('f0000000-0000-4000-8000-00000000000c', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'e0000000-0000-4000-8000-000000000007', 'e0000000-0000-4000-8000-000000000009', 1, null, null),
  ('f0000000-0000-4000-8000-00000000000d', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'e0000000-0000-4000-8000-000000000008', 'e0000000-0000-4000-8000-000000000009', 1, null, null),
  ('f0000000-0000-4000-8000-00000000000e', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000001', 'e0000000-0000-4000-8000-000000000009', 'e0000000-0000-4000-8000-00000000000b', 1, null, null);



update public.processes set live_revision_id = 'd0000000-0000-4000-8000-000000000001' where id = 'c0000000-0000-4000-8000-000000000001';

commit;
