/** Labels for step and edge fields, used to describe conflicts and draft changes. */
export const FIELD_LABELS: Record<string, string> = {
  name: "name",
  kind: "kind",
  outcome: "outcome",
  role_id: "role",
  person_id: "pinned person",
  work_hours: "hands-on time",
  work_dist: "hands-on distribution",
  "work_params.cv": "hands-on variability",
  "work_params.min": "hands-on minimum",
  "work_params.mode": "hands-on most likely",
  "work_params.max": "hands-on maximum",
  wait_hours: "wait time",
  wait_dist: "wait distribution",
  "wait_params.cv": "wait variability",
  "wait_params.min": "wait minimum",
  "wait_params.mode": "wait most likely",
  "wait_params.max": "wait maximum",
  rework_rate: "rework rate",
  rework_to_step_id: "rework target",
  tool: "tool",
  notes: "notes",
  sla_hours: "SLA",
  current_wip: "current WIP",
  x: "position",
  y: "position",
  assumption: "estimate",
  conflict: "conflict",
  probability: "branch probability",
  condition_tag: "condition tag",
  label: "label",
  from_step_id: "start of the connection",
  to_step_id: "end of the connection",
};
